config/routes.rb
Fivesecondcoder::Application.routes.draw do
  resources :cards do
  	get 'random', :on => :collection
		resources :answers
	end
  get "static_deck/home"
  root :to => 'static_deck#home'

end

app/models/answer.rb
class OverlapValidator < ActiveModel::Validator
	def validate(record)
		record.card.answers.each { |answer|
			(answer.start_offset..answer.end_offset).each { |existing_offset|
				(record.start_offset..record.end_offset).each { |validating_offset|
					if existing_offset == validating_offset
						record.errors[:base] << "Answers cannot overlap"
					end
				}
			}
		}
	end
end

class Answer < ActiveRecord::Base
	include ActiveModel::Validations
	attr_accessible :card_id, :start_offset, :end_offset
  belongs_to :card
	validates_presence_of :card_id, :start_offset, :end_offset
	validates :start_offset, :numericality => { :only_integer => true }
	validates :end_offset, :numericality => { :only_integer => true, :greater_than_or_equal_to => :start_offset }
	validates_with OverlapValidator
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :code, :task, :split_schema_id
  has_many :answers, dependent: :destroy
  belongs_to :split_schema
  validates_presence_of :code, :task, :split_schema_id
  after_initialize :init

  def init
  	self.split_schema ||= SplitSchema.default.first
  end

	def split_lines
		self.code.split(/\r\n/)	
	end

	def split_substrings(line)
		self.split_schema.is_regex ? line.split(/#{self.split_schema.regex}/) : [line]
	end

	def tokenized_code
		code_array = []
		self.split_lines.each { |line|
			line_array = []
			split_substrings(line).each { |substring|
				line_array.push(substring)
			}
			code_array.push(line_array)
		}
		code_array
	end

	def as_json(options = {})
		super(methods: :tokenized_code, except: :split_schema_id, include: :answers)
	end
end

app/models/split_schema.rb
class SplitSchema < ActiveRecord::Base
  attr_accessible :name, :regex, :is_regex
  
  validates_presence_of :name

  has_many :cards

  scope :default, where("name = 'Default'")
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_filter :get_card

	def get_card
		@card = Card.find(params[:card_id])
	end

  # GET /answers
  # GET /answers.json
  def index
    @answers = @card.answers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = @card.answers.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = @card.answers.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @card.answers.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@card, @answer], notice: 'Answer was successfully created.' }
        format.json { render json: [@card, @answer], status: :created, location: [@card, @answer] }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to card_answers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/random/1.json
  def random
  	offset = rand(Card.count)
  	@card = Card.first(:offset => offset)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_deck_controller.rb
class StaticDeckController < ApplicationController
  def home
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/static_deck_helper.rb
module StaticDeckHelper
end

app/views/answers/_form.html.erb
<%= form_for([@card, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :start_offset %><br />
		<%= f.text_field :start_offset %>
	</div>
	<div class="field">
		<%= f.label :end_offset %><br />
		<%= f.text_area :end_offset %><br />
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', [@card, @answer] %> |
<%= link_to 'Back', card_answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Start Offset</th>
    <th>End Offset</th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
		<td><%= answer.start_offset %></td>
		<td><%= answer.end_offset %></td>
    <td><%= link_to 'Show', [@card, answer] %></td>
    <td><%= link_to 'Edit', edit_card_answer_path(@card, answer) %></td>
    <td><%= link_to 'Destroy', [@card, answer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_card_answer_path(@card) %> |
<%= link_to 'Card', card_path(@card) %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', card_answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Start Offset:</b>
	<%= @answer.start_offset %>
</p>

<p>
	<b>End Offset:</b>
	<%= @answer.end_offset %>
</p>

<%= link_to 'Edit', edit_card_answer_path(@answer) %> |
<%= link_to 'Back', card_answers_path %>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_area :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.task %></td>
    <td><%= card.code %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<%= javascript_tag do %>
	window.cardAnswers = <%= raw @card.answers.select("start_offset, end_offset").to_json %>
	window.cardId = <%= raw @card.id.to_json %>
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @card.task %>
</p>

<p>
<b>Code:</b></br/>
</p>

<div id="start_prompt">Click on the start point of the answer.</div>
<div id="end_prompt" class="hidden">Now select the end point of the answer.</div>
<div id="overlap_error" class="hidden">Error: answers cannot overlap.</div>

<div id="card_code">
	<ol>
		<% offset = 0 %>
		<% @card.tokenized_code.each do |line| %>
			<li><% line.each do |substring| %><span id= "<%= offset %>" class="card_code_snippet"><%= substring == "\t" ? "  " : substring %></span><% offset+= 1 %><% end %></li>
		<% end %>
	</ol>
</div>

<div id="card_answers">
	<ol>
		<% @card.answers.each_with_index do |answer, index| %>
			<li>Start Offset:<%= answer.start_offset %> End Offset:<%= answer.end_offset %></li>
		<% end %>
	</ol>
</div>

<div>
<a id="save_prompt" class="hidden" href="#">Save</a>
</div>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %> |
<%= link_to 'Answers', card_answers_path(@card) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fivesecondcoder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<header>
	<h1>Five Second Coder</h1>
	<%= link_to 'All Cards', cards_path %> |
	<%= link_to 'Play!', static_deck_home_path %>
</header>

<body>

<%= yield %>

</body>
</html>

app/views/static_deck/home.html.erb
<hr>

<div id="card">
	<a id="start" href="#">Start!</a>
	<div id="task">
	</div>

	<div id="code_window" class="hidden">
		<ol id="code">
		</ol>
	</div>

	<div id="score_window">
	</div>
</div>